# Importacion de datos

In [1]:
import pandas as pd

In [8]:
datos =pd.read_csv('Datos.csv')
datos.head()

,Marca temporal,Nombre,Correo electrónico,edad,Que tipo de celular tiene,operador
0,6/03/2026 18:33:13,Daniel Messi,Danielmessi@gmail.com,10,iphone,Claro
1,6/03/2026 18:35:12,María López,marialopez@gmail.com,28,Samsung,Movistar
2,6/03/2026 18:36:45,Carlos Ramírez,cramirez@hotmail.com,35,Xiaomi,Claro
3,6/03/2026 18:37:30,Laura Gómez,lauragomez@yahoo.com,22,iPhone,Tigo
4,6/03/2026 18:38:05,Andrés Martínez,amartinez@gmail.com,41,Motorola,Movistar

In [9]:
datos.tail()

,Marca temporal,Nombre,Correo electrónico,edad,Que tipo de celular tiene,operador
4,6/03/2026 18:38:05,Andrés Martínez,amartinez@gmail.com,41,Motorola,Movistar
5,6/03/2026 18:39:10,Valentina Torres,valentina.torres@gmail.com,19,Samsung,Claro
6,6/03/2026 18:40:22,Jorge Castillo,jorgecastillo@hotmail.com,33,Huawei,Tigo
7,6/03/2026 18:41:18,Natalia Rojas,natalia.rojas@gmail.com,27,Xiaomi,Movistar
8,6/03/2026 18:42:07,Felipe Herrera,fherrera@yahoo.com,38,iPhone,Claro

In [41]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Marca temporal             9 non-null      object
 1   Nombre                     9 non-null      object
 2   Correo electrónico         9 non-null      object
 3   edad                       9 non-null      int64
 4   Que tipo de celular tiene  9 non-null      object
 5   operador                   9 non-null      object
dtypes: int64(1), object(5)
memory usage: 564.0+ bytes

In [14]:
datos.describe()

            edad
count   9.000000
mean   28.111111
std     9.905105
min    10.000000
25%    22.000000
50%    28.000000
75%    35.000000
max    41.000000

In [40]:
datos['edad'] = datos['edad'].astype(int)